branch-defaults:
  default:
    environment: production
    group_suffix: null
global:
  application_name: Django app
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
